### ISSUE TITLE
db conn to remote instance

### ISSUE THREAD

**Issue by UmutAlihan** [lamarios/SpendSpentSpent#19]
Hi,

I found your minimal app from one of reddit self-hosted forums.

It is much appreciated and really a solution to a very specific niche. Many thanks for your contribution!

My issue here is about connecting to remote postgresql instance which I am hosting on another server, is it possible?

**Comment by lamarios** [comment]
At the moment no. It only support mysql and H2DB. Adding postgres shouldn't be much work but still needs to be done. I'll try to find time next week.

**Comment by lamarios** [comment]
I had a look and because of the mess that is my backend wortjs with the database in some aspect. It won't be possible to implement  postgres for now. I'll close the issue but I will keep this in mind for when I have time to sort the backend first.
