### ISSUE TITLE
Feature Request: Add your own or more categories

### ISSUE THREAD

**Issue by michi29** [lamarios/SpendSpentSpent#22]
First of all, I love this project and use it every day :)
I would appreciate if I could add my own categories. I could either give it a name by myself or by an icon. For the latter, you could add more icons top choose from.

**Comment by lamarios** [comment]
Hi. Thanks! Glad that you like the project.

Adding category just as a name might be a bit weird and custom icons might be doable but would need quite a bit of work.

I was planning on adding more icons but I want to gather a list first as I'm asking a designer to do those so if you have any category that you'd wish to have please list it down with maybe a reference of what you expect if it's not obvious.

**Comment by michi29** [comment]
Some ideas might be:

- In transport category: a road bike icon for bikes and its expenses
- In the healh category I would like to have a more generous icon (maybe a hospital icon) for more generous expenses like health insurance
- In education category: a book icon for all kind of books
- If you go out: maybe a cafe icon and a disco ball icon for partying and stuff like that

**Comment by lamarios** [comment]
I added a new file with [new icons](https://github.com/lamarios/SpendSpentSpent/blob/master/new-icons.md) wish list. Feel free to make any PR if you have new icon ideas. I'll reach out to the designer if the list reaches at least 20 icons.

**Comment by lamarios** [comment]
By the way did  you use it when it was the old web version ? If yes how do you like the new one (and mobile apps too) ?
