### ISSUE TITLE
input-modal truncated on small screens - unable to save

### ISSUE THREAD

**Issue by kkneutgen** [lamarios/SpendSpentSpent#27]
Hi,
I like this project.
Unfortunately the user-input does not work on small screens: the bottom is truncated and you can't scroll. So there is no way to save. 
This happens on my iPhone-SE, both with the app and in the browser. Is there any chance to fix the responsibility with an upcoming release?
Thank you.

![screenshot_sss](https://user-images.githubusercontent.com/11966701/187071359-485cb2b2-fc6a-4921-af7c-fe40e1469321.png)

**Comment by lamarios** [comment]
Hi,

Sure. I'll have a look into it.

**Comment by lamarios** [comment]
A possible fix is currently in the app stores review (v1.2.8). It usually takes up to a couple of days for the new app to be propagated. Let me know if it fixes it. 

I don't have iPhones and a proper mac setup to test this properly. So i did it based on the information i found on iPhone SE's viewport.

**Comment by kkneutgen** [comment]
Thank you, I will check as soon as it's available in the store.

In the browser it's still truncated (current docker-image), hiding the navbar does not work either. Maybe place the save-button in the top-left next to the category-icon?
My workaround is scaling the view to 75% in safari.

![SpendSpentSpent](https://user-images.githubusercontent.com/11966701/187077247-27bdda4d-920d-40f6-9d57-ee350380973f.png)

**Comment by lamarios** [comment]
Alright, Let's see if it works fine for the app. I'll still try to make it scale better on even smaller screen.

**Comment by kkneutgen** [comment]
Yes, it works for the app now:

![SpendSpentSpent_2](https://user-images.githubusercontent.com/11966701/187410025-266e1096-f7cd-490b-9473-07f4a5c452fc.png)

**Comment by lamarios** [comment]
ok, not great though haha . I'll try to make this better.
