### ISSUE TITLE
API or something to add transactions from external sources

### ISSUE THREAD

**Issue by leshik** [lamarios/SpendSpentSpent#28]
An exciting project, thanks!
Is there a way to enter transactions from external sources? I'm thinking of implementing some sort of bank sync.

**Comment by lamarios** [comment]
You can use the api of the project. You can try it out here: https://<your-backend-url>/swagger-ui/  or try the with the demo here: https://sss.ftpix.com/swagger-ui/

Use the /Login endpoint with demo@demo.com  and demo as password. Copy the token  in the response


Then click authorize and type 
```
Bearer <token you copied>
```

Then you can try the other endpoints.

**Comment by leshik** [comment]
That's cool. Do you have any plans to add accounts (e.g. Cash, Bank, etc.), or you're intentionally avoiding this to keep the app simple?

**Comment by lamarios** [comment]
My goal is to keep it as simple as possible. Just track expenses and that's it.

Though adding accounts is something that could be nice if I can think of a way to do this without disturbing the flow of the app.

But I can't commit on anything so I'd assume that this is not planned if I were you :)
