### ISSUE TITLE
Share expenses

### ISSUE THREAD

**Issue by sneffetsd** [lamarios/SpendSpentSpent#31]
Hi, I'm using sss to track expenses, but would be nice to share the same expense database between users.
Me and my wife could track together. Is that possible?

**Comment by lamarios** [comment]
no unfortunately it's not possible at the moment. Given the time i have to work on this project. I don;t think that's something I'll be doing any time soon as it's not as straight forward to implement.

You both can share the same account though. There's no limitations on the number of active sessions.

**Comment by sneffetsd** [comment]
Nice to know. I didn't think about that.
If there is not problem logging in both with the same account it will be fine.
