### ISSUE TITLE
Docker - No spending category appears and there is no way to add.

### ISSUE THREAD

**Issue by tsuihak** [lamarios/SpendSpentSpent#41]
I am using Docker to install the program, the web page starts, created the administrator account but the spending categories do not appear and the add button does not appear either.
<img width="570" alt="Captura de Tela 2024-11-28 às 10 52 25" src="https://github.com/user-attachments/assets/65dcc1b2-96fb-4ed8-a0a2-c56be4c2d3da">

In recurring expenses I can't add anything either either. I can't leave it the way it is in the demo and I've tried several times.
<img width="566" alt="Captura de Tela 2024-11-28 às 10 52 42" src="https://github.com/user-attachments/assets/f7cab49f-6ac3-40c0-b638-93f428130fce">

I'm sorry for Google Translator English. Follows copy of my docker configuration file.
<img width="365" alt="Captura de Tela 2024-11-28 às 10 58 53" src="https://github.com/user-attachments/assets/8b4d9cca-0ec9-4621-b232-df7fe695540b">

**Comment by lamarios** [comment]
You setup looks fine. There is a bug I need to fix that prevents the button to add categories on a new install to show up. 

I'll try to fix it over the week end.

**Comment by tsuihak** [comment]
Thank you for trying to correct. I installed an ancient hub.docker version working perfectly. But this version is not updated for 4 years and changes only one letter, SpendSpendSpent instead of SpendSpentSpent.

https://hub.docker.com/r/gonzague/spendspendspent

**Comment by tsuihak** [comment]
Just to add the discussion more, I took the test with version 1.4.1 build 70 and worked perfectly.

https://hub.docker.com/layers/gonzague/spendspentspent/70/images/sha256-f91ade119205dbb5ed8c34ca9406568ecef37f5017b74bf0a900f9241c82132a?context=explore

**Comment by lamarios** [comment]
alright, cool that you found a solution. i'm going to release a fix so next time somebody starts fresh they don't have problems
